//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutdownController.Resources.SettingsStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShutdownController.Resources.SettingsStrings.SettingsStrings", typeof(SettingsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string applicationSettings {
            get {
                return ResourceManager.GetString("applicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on Windows startup.
        /// </summary>
        public static string autoStartActive {
            get {
                return ResourceManager.GetString("autoStartActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable push-messages.
        /// </summary>
        public static string disablePushMessages {
            get {
                return ResourceManager.GetString("disablePushMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On closing still run in background.
        /// </summary>
        public static string onClosing {
            get {
                return ResourceManager.GetString("onClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Startup.
        /// </summary>
        public static string onStartUp {
            get {
                return ResourceManager.GetString("onStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save performance.
        /// </summary>
        public static string savePerformance {
            get {
                return ResourceManager.GetString("savePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        public static string startMinimized {
            get {
                return ResourceManager.GetString("startMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On closing programm is minimized in your system tray on your taskbar..
        /// </summary>
        public static string toastNotificationOnClosing {
            get {
                return ResourceManager.GetString("toastNotificationOnClosing", resourceCulture);
            }
        }
    }
}
