//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutdownController.Resources.MainWindowStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShutdownController.Resources.MainWindowStrings.MainWindowStrings", typeof(MainWindowStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App started!.
        /// </summary>
        public static string appStarted {
            get {
                return ResourceManager.GetString("appStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info button.
        /// </summary>
        public static string infoButton {
            get {
                return ResourceManager.GetString("infoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string isStillRunningInBackground {
            get {
                return ResourceManager.GetString("isStillRunningInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action will perform in ....
        /// </summary>
        public static string MBActionWillPerformIn {
            get {
                return ResourceManager.GetString("MBActionWillPerformIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press me....
        /// </summary>
        public static string pressMe {
            get {
                return ResourceManager.GetString("pressMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schutdown.
        /// </summary>
        public static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string sleep {
            get {
                return ResourceManager.GetString("sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string ttClock {
            get {
                return ResourceManager.GetString("ttClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ttClose {
            get {
                return ResourceManager.GetString("ttClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down- upload observing.
        /// </summary>
        public static string ttDownUp {
            get {
                return ResourceManager.GetString("ttDownUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read write observing.
        /// </summary>
        public static string ttReadWrite {
            get {
                return ResourceManager.GetString("ttReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ttSettings {
            get {
                return ResourceManager.GetString("ttSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string ttTimer {
            get {
                return ResourceManager.GetString("ttTimer", resourceCulture);
            }
        }
    }
}
